# Generated by Django 2.1 on 2020-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='')),
                ('ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('type', models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6')], max_length=4)),
                ('continent_code', models.CharField(default='', max_length=2)),
                ('continent_name', models.CharField(default='', max_length=50)),
                ('country_code', models.CharField(default='', max_length=2)),
                ('country_name', models.CharField(default='', max_length=50)),
                ('region_code', models.CharField(default='', max_length=50)),
                ('region_name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('zip', models.CharField(default='', max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
    ]
